"""followers

Revision ID: 304000c2deaf
Revises: 21c867bd108d
Create Date: 2020-08-08 17:05:32.050601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304000c2deaf'
down_revision = '21c867bd108d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followes',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followes')
    # ### end Alembic commands ###
